name: Composite Action for Testing
runs:
  using: 'composite'
  steps:
    - name: Run Action
      uses: __CUSTOM_ACTION_REPO__@__GITHUB_SHA__
      id: sample
      with:
        milliseconds: 5000
    - name: Test Outputs
      run: |
        if ("${{ steps.sample.outputs.time }}") {
          Write-Output "Output Value Found [${{ steps.sample.outputs.time }}]"
        } else {
          Write-Error "No output value found"
          exit 1
        }
      shell: pwsh
